version: '3.6'
services:

  # ==== WATCHTOWER ====
  watchtower:
    image: node:16
    working_dir: /home/node/app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 127.0.0.1:5000:5000
    environment:
      WATCHTOWER_SECRET: watchtowersecretforhash
      WATCHTOWER_ADMIN_USER: admin
      WATCHTOWER_ADMIN_PASS: password
      HASURA_URL: http://localhost:8080
      HASURA_ADMIN_SECRET: myadminsecret
    volumes:
      # Server files
      - ./app:/home/node/app
      # Project files (backups)
      - ./project:/home/node/project
        
  # ==== HASURA ====
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.2.0
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecret
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/database
    depends_on:
      postgres:
        condition: service_healthy